### ISSUE TITLE
FPGA version error with USRP B200

### ISSUE THREAD

**Issue by beged** [osqzss/gps-sdr-sim#216]
Hi All, I got this error:
[INFO] [UHD] Win32; Microsoft Visual C++ version 14.0; Boost_106000; UHD_3.13.0.1-0-unknown
[INFO] [B200] Detected Device: B200
[INFO] [B200] Operating over USB 3.
Traceback (most recent call last):
 File "gps-sdr-sim-uhd.py", line 90, in <module>
   tb = top_block(options)
 File "gps-sdr-sim-uhd.py", line 23, in __init__
   self.uhd_usrp_sink = uhd.usrp_sink(options.args, uhd.io_type_t.COMPLEX_FLOAT32, 1)
 File "C:\Program Files\GNURadio-3.7\lib\site-packages\gnuradio\uhd\__init__.py", line 122, in constructor_interceptor
   return old_constructor(*args)
 File "C:\Program Files\GNURadio-3.7\lib\site-packages\gnuradio\uhd\uhd_swig.py", line 3125, in make
   return _uhd_swig.usrp_sink_make(*args)
RuntimeError: RuntimeError: Expected FPGA compatibility number 15, but got 16:
The FPGA build is not compatible with the host code build.

should I downgrade my FPGA image?
othervise my gnuradio (grc) installation works fine with this B200 hw... win10 64bit
any suggestions?

**Comment by beged** [comment]
I had two different UHD installation, I had to force to use the one with GRC install by setting UHD_PKG_PATH env variable to C:\Program Files\GNURadio-3.7
